package RobotSimulation;
import javax.swing.*;
import java.io.*;
import java.util.Random;
import java.util.ArrayList;

public class RobotArena implements Serializable {
    private int x_size;
    private int y_size;
    private ArrayList<Robot> robot;

    public int getNumRobots() {
        return robot.size();
    }

    public int getX_size() {
        return x_size;
    }

    public int getY_size() {
        return y_size;
    }

    public RobotArena(int x_size, int y_size) {
        this.x_size = x_size;
        this.y_size = y_size;
        //this.numRobots = numRobots;
        robot = new ArrayList<>();
    }

    /**
     * Is the robot at this x, y position?
     * @param sx    x position.
     * @param sy    y position.
     * @param rNum  the robot being tested.
     * @return      true if robot at xy is found, false otherwise.
     */
    public boolean isHere(int rNum, int sx, int sy) {
        if(rNum < robot.size()) {
            Robot r = robot.get(rNum);
            return r.getX() == sx && r.getY() == sy;
        }
        return false;
    }

    public void addRobot(int num) {
        Random randomGenerator = new Random();
        int rX, rY;
        Robot newRobot;
        do {
            rX = randomGenerator.nextInt(x_size-2)+1;
            rY = randomGenerator.nextInt(y_size-2)+1;
            newRobot = new Robot(num, rX, rY, Direction.getRandomDirection());
        }
        while (isHere(num -1, rX, rY));

        robot.add(newRobot);
    }

    public String toString(int numRobots) {
        System.out.println("Arena of size " + x_size + " by " + y_size + " with "
                + numRobots + " robot(s)");
        String returnstr = "";
        for (int i = 0; i < numRobots; i++) {
            returnstr += robot.get(i) + "\n";   // Appending robot information to return string.
        }
        return returnstr;
    }

    public void showRobots(ConsoleCanvas c) {
        for (Robot value : robot) {
            //Accessing robot number i in robot and accessing the displayRobot method.
            value.displayRobot(c);
        }
    }

    private boolean isWithinBounds(int x, int y) {
        return x > 0 && x < x_size-1 && y > 0 && y < y_size-1; // checks whether new x, y coords are within the arena.
    }

    private boolean isOccupied(int x, int y, Robot testRobot) {
        for (Robot other : robot) {
            if(other != testRobot && other.getX() == x && other.getY() == y) {
                return true; // The x, y coords are occupied by another robot.
            }
        }
        return false;
    }

    public boolean canMoveHere(Robot r){
        int[] newPos = r.calculateNewPosition();
        int newX = newPos[0];
        int newY = newPos[1];
        // Uses the x, y coords generated by calculateNewPosition()

        return isWithinBounds(newX, newY) && !isOccupied(newX, newY, r);
    }

    public void moveAll(RobotArena arena) {
        for(Robot item : arena.robot) {
            item.tryToMove(arena);
        }
    }

    // Method to save the current arena state
    public void saveArena() {
        // Creating an instance of JFileChooser allowing for file management.
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save arena to file"); // This sets the title of the dialog box

        // This variable is used to save the user choice.
        int userSelect = fileChooser.showSaveDialog(null);
        // And this executes if the user chooses to save the file.
        if(userSelect == JFileChooser.APPROVE_OPTION) {
            // This variable saves the file path.
            String fileName = fileChooser.getSelectedFile().getAbsolutePath();

            // This try catch block ensures that file output stream executes properly and closes file stream.
            try(FileOutputStream fileOut = new FileOutputStream(fileName);
                ObjectOutputStream out = new ObjectOutputStream(fileOut)){
                out.writeObject(this);  // This is the line that writes the object into the file.
                System.out.println("Saved arena to " + fileName);
            } catch (IOException ex) {
                // prints the stack trace if an error occurs during the save process.
                // I can change this to a println for a robust method of error logging.
                ex.printStackTrace();
            }

        }
    }

    // Method to load an arena state from a file.
    public static RobotArena loadArena() {
        System.out.println("Attempting to load an arena...");

        // Creates an instance of JFileChooser.
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Load arena from file");
        // Saves the user choice
        int userSelect = fileChooser.showOpenDialog(null);

        // This block will execute if the user chooses a file.
        if(userSelect == JFileChooser.APPROVE_OPTION) {
            String fileName = fileChooser.getSelectedFile().getAbsolutePath();  // Saves the file path.
            // Ensuring the file stream executes properly and closes once finished
            try(FileInputStream fileIn = new FileInputStream(fileName);
                ObjectInputStream in = new ObjectInputStream(fileIn)) {
                // Need to create file input stream AND object input stream

                RobotArena arena = (RobotArena) in.readObject(); // This deserealization the arena object.
                System.out.println("Loaded arena from " + fileName);
                return arena;
            } catch (IOException | ClassNotFoundException ex) {
                ex.printStackTrace();
            }
        } else {
            System.out.println("No file selected");
        }
        System.out.println("Loading failed.");
        return null;
    }

    public static void main(String[] args) {
        RobotArena a = new RobotArena(20,20);
        a.addRobot(1);
        a.addRobot(2);
        a.addRobot(3);
        System.out.println(a.toString(3));
    }
}
